import {Component} from 'react'
class HadeethContainer extends Component {
    state = {  }
    render() { 
        return (
          <div className="Centered">
           
           <div className="container-with-centered-content">

            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
            hello world
           </div>
          </div>
          );
}
}

 
export default HadeethContainer;